require: rubocop-rspec

RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 4

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'vendor/**/*'
  DisplayCopNames: true
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Documentation:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
